### ISSUE TITLE
Таск clean не используется

### ISSUE THREAD

**Issue by 3rdTheMagical** [Insayt/frontend-devil#1]
При запуске проекта попка build не очищается. При удалении файлов из src не удаляются аналогичные из build.

**Comment by Insayt** [comment]
Таск clean создан просто для удобства. Нет смысла при каждой итерации удалять весь build. 
При удалении из src действительно не удаляются файлы из build, потому что я так и не нашел нормального способа отследить из node момент удаления файла. Clean как раз и нужен, что бы периодически подчищать build от скопившихся, неиспользованных файлов
