### ISSUE TITLE
Broken @import declaration

### ISSUE THREAD

**Issue by Splintex** [Insayt/frontend-devil#2]
I have tried  'gulp' command after 'npm install'

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Broken @import declaration of "../../bower_components/normalize.css/normalize.css"
PS C:\Users\Eugene\documents\test3>

**Comment by Splintex** [comment]
It's my mistake, sorry)

**Comment by myaskevich** [comment]
@Splintex What was that?

**Comment by Splintex** [comment]
@myaskevich I don't remember
